version: '3.8'

services:
  app:
    build: .
    container_name: aetherpulse_app
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/aetherpulse
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mongodb
      - redis
    volumes:
      - .:/app

  mongodb:
    image: mongo:6.0
    container_name: aetherpulse_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7.2
    container_name: aetherpulse_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mongo_data:
  redis_data: 